/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabi Curiel
 */
public class Views extends javax.swing.JFrame {

    /**
     * Creates new form ViewE
     */
    public Views() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        j_panel_agenda = new javax.swing.JPanel();
        jl_nombre_persona = new javax.swing.JLabel();
        jtf_nombre_agenda = new javax.swing.JTextField();
        jl_email = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        Jb_guardar_registro = new javax.swing.JButton();
        jb_nuevo_registro = new javax.swing.JButton();
        Jb_primee_registro = new javax.swing.JButton();
        Jb_anterior = new javax.swing.JButton();
        Jb_siguiente_registro = new javax.swing.JButton();
        Jb_ultimo_registro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        j_panel_agenda.setBackground(new java.awt.Color(255, 255, 255));
        j_panel_agenda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        j_panel_agenda.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N

        jl_nombre_persona.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jl_nombre_persona.setText("Nombre:");

        jl_email.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jl_email.setText("Email:");

        Jb_guardar_registro.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        Jb_guardar_registro.setText("Guardar");
        Jb_guardar_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jb_guardar_registroActionPerformed(evt);
            }
        });

        jb_nuevo_registro.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jb_nuevo_registro.setText("Nuevo");

        Jb_primee_registro.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        Jb_primee_registro.setText("|<");

        Jb_anterior.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        Jb_anterior.setText("<<");

        Jb_siguiente_registro.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        Jb_siguiente_registro.setText(">>");

        Jb_ultimo_registro.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        Jb_ultimo_registro.setText(">|");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("AGENDA VERSION 1");

        javax.swing.GroupLayout j_panel_agendaLayout = new javax.swing.GroupLayout(j_panel_agenda);
        j_panel_agenda.setLayout(j_panel_agendaLayout);
        j_panel_agendaLayout.setHorizontalGroup(
            j_panel_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_agendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(j_panel_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(j_panel_agendaLayout.createSequentialGroup()
                        .addComponent(Jb_primee_registro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_nuevo_registro)
                        .addGap(52, 52, 52)
                        .addComponent(Jb_guardar_registro))
                    .addGroup(j_panel_agendaLayout.createSequentialGroup()
                        .addGroup(j_panel_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(j_panel_agendaLayout.createSequentialGroup()
                                .addComponent(jl_nombre_persona)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_nombre_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(j_panel_agendaLayout.createSequentialGroup()
                                .addComponent(jl_email)
                                .addGap(18, 18, 18)
                                .addGroup(j_panel_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(j_panel_agendaLayout.createSequentialGroup()
                                        .addComponent(Jb_anterior)
                                        .addGap(35, 35, 35)
                                        .addComponent(Jb_siguiente_registro)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jtf_email))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jb_ultimo_registro)))
                .addGap(133, 133, 133))
            .addGroup(j_panel_agendaLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        j_panel_agendaLayout.setVerticalGroup(
            j_panel_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_panel_agendaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(j_panel_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nombre_persona)
                    .addComponent(jtf_nombre_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(j_panel_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_email)
                    .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(j_panel_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jb_primee_registro)
                    .addComponent(Jb_anterior)
                    .addComponent(Jb_siguiente_registro)
                    .addComponent(Jb_ultimo_registro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addGroup(j_panel_agendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_nuevo_registro)
                    .addComponent(Jb_guardar_registro)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(j_panel_agenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jb_guardar_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb_guardar_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jb_guardar_registroActionPerformed

    private void Jtf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_emailActionPerformed

    private void Jb_primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jb_primeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jb_primeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Views.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Views().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Jb_anterior;
    public javax.swing.JButton Jb_guardar_registro;
    public javax.swing.JButton Jb_primee_registro;
    public javax.swing.JButton Jb_siguiente_registro;
    public javax.swing.JButton Jb_ultimo_registro;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel j_panel_agenda;
    public javax.swing.JButton jb_nuevo_registro;
    public javax.swing.JLabel jl_email;
    public javax.swing.JLabel jl_nombre_persona;
    public javax.swing.JTextField jtf_email;
    public javax.swing.JTextField jtf_nombre_agenda;
    // End of variables declaration//GEN-END:variables
}
